### ISSUE TITLE
Alchemy mixes Brew and Potion

### ISSUE THREAD

**Issue by GodNooNoo** [Trimps/bug-tracker#192] opened 2023-01-07 13:51 UTC
As seen in the image below the text for Potion of the Void states that it nullifies "Potions", but the only stat increase comes from Brews. In the sentence thereafter "Potions" referrers specifically only to Potions and not to Brews. Does not seem coherent.

![image](https://user-images.githubusercontent.com/10705372/211154043-2fa1c9e4-983f-4b09-a088-bca32c2ad178.png)

**Comment by grabz-dev** [comment] 2023-01-07 13:59
Duplicate of #145

**Comment by Trimps** [comment] 2023-01-09 06:12
Fixed on 5.9.0 test server, thank you!

**Closed as completed by Trimps** 2023-01-09 06:12 UTC
Labels: typo
